/*
  # Seed Initial Data

  1. Product Categories
    - Industrial Pumps
    - Compressors
    - Conveyor Systems
    - Industrial Valves
    - Power Generation
    - Material Handling

  2. Sample Products
    - Sample products for each category

  3. Sample Blog Posts
    - Technical articles for content demonstration
*/

INSERT INTO product_categories (id, name, slug, description, display_order, is_active) VALUES
  ('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'Industrial Pumps', 'industrial-pumps', 'High-performance pumping solutions for demanding industrial applications. Our range includes centrifugal, positive displacement, and specialty pumps designed for reliability and efficiency.', 1, true),
  ('b2c3d4e5-f6a7-8901-bcde-f12345678901', 'Compressors', 'compressors', 'Industrial-grade air and gas compressors engineered for continuous operation. From rotary screw to reciprocating models, built for maximum uptime.', 2, true),
  ('c3d4e5f6-a7b8-9012-cdef-123456789012', 'Conveyor Systems', 'conveyor-systems', 'Complete conveyor solutions for material transport and handling. Belt, roller, and modular systems designed for your specific workflow requirements.', 3, true),
  ('d4e5f6a7-b8c9-0123-def0-234567890123', 'Industrial Valves', 'industrial-valves', 'Precision valve solutions for flow control in critical applications. Gate, ball, butterfly, and check valves meeting international standards.', 4, true),
  ('e5f6a7b8-c9d0-1234-ef01-345678901234', 'Power Generation', 'power-generation', 'Reliable power generation equipment including diesel generators, turbines, and backup power systems for industrial facilities.', 5, true),
  ('f6a7b8c9-d0e1-2345-f012-456789012345', 'Material Handling', 'material-handling', 'Complete material handling solutions including hoists, cranes, forklifts, and automated systems for efficient operations.', 6, true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO products (name, slug, category_id, short_description, full_description, specifications, is_featured, is_active) VALUES
  ('Centrifugal Process Pump CP-500', 'centrifugal-process-pump-cp-500', 'a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'Heavy-duty centrifugal pump designed for continuous industrial process applications with high flow rates and exceptional reliability.', '<h3>Overview</h3><p>The CP-500 Centrifugal Process Pump represents the pinnacle of industrial pumping technology. Engineered for demanding process applications, this pump delivers consistent performance in chemical processing, water treatment, and general industrial service.</p><h3>Technical Specifications</h3><table><tr><th>Parameter</th><th>Value</th></tr><tr><td>Flow Rate</td><td>50-500 GPM</td></tr><tr><td>Head</td><td>Up to 250 ft</td></tr><tr><td>Temperature Range</td><td>-20°F to 350°F</td></tr><tr><td>Materials</td><td>316SS, CD4MCu, Hastelloy</td></tr></table><h3>Features</h3><ul><li>Back pull-out design for easy maintenance</li><li>API 610 compliant construction</li><li>Mechanical seal options for all services</li><li>Baseplate mounted for stability</li></ul>', '{"flow_rate": "50-500 GPM", "head": "Up to 250 ft", "temperature": "-20°F to 350°F", "materials": ["316SS", "CD4MCu", "Hastelloy"], "compliance": ["API 610", "ASME"]}', true, true),
  
  ('Rotary Screw Compressor RSC-200', 'rotary-screw-compressor-rsc-200', 'b2c3d4e5-f6a7-8901-bcde-f12345678901', 'Energy-efficient rotary screw compressor with variable speed drive for optimized air delivery and reduced operating costs.', '<h3>Overview</h3><p>The RSC-200 Rotary Screw Compressor delivers superior compressed air performance with industry-leading energy efficiency. Variable speed drive technology ensures optimal air delivery matched to your demand.</p><h3>Technical Specifications</h3><table><tr><th>Parameter</th><th>Value</th></tr><tr><td>Capacity</td><td>200-850 CFM</td></tr><tr><td>Pressure</td><td>100-175 PSI</td></tr><tr><td>Motor Power</td><td>50-200 HP</td></tr><tr><td>Noise Level</td><td>&lt;75 dBA</td></tr></table><h3>Features</h3><ul><li>Variable Speed Drive (VSD) technology</li><li>Integrated air dryer option</li><li>Remote monitoring capability</li><li>Low maintenance airend design</li></ul>', '{"capacity": "200-850 CFM", "pressure": "100-175 PSI", "motor_power": "50-200 HP", "noise_level": "<75 dBA", "features": ["VSD", "Remote Monitoring"]}', true, true),
  
  ('Heavy-Duty Belt Conveyor BC-3000', 'heavy-duty-belt-conveyor-bc-3000', 'c3d4e5f6-a7b8-9012-cdef-123456789012', 'Robust belt conveyor system engineered for high-volume material transport in mining, aggregate, and heavy industrial applications.', '<h3>Overview</h3><p>The BC-3000 Heavy-Duty Belt Conveyor is designed for the most demanding material handling applications. Built to withstand continuous operation in harsh environments while maintaining reliable throughput.</p><h3>Technical Specifications</h3><table><tr><th>Parameter</th><th>Value</th></tr><tr><td>Belt Width</td><td>24" to 72"</td></tr><tr><td>Capacity</td><td>Up to 3000 TPH</td></tr><tr><td>Belt Speed</td><td>100-600 FPM</td></tr><tr><td>Length</td><td>Custom to 2000 ft</td></tr></table><h3>Features</h3><ul><li>Heavy-gauge steel construction</li><li>Self-cleaning return idlers</li><li>Multiple drive configurations</li><li>Integrated safety systems</li></ul>', '{"belt_width": "24\" to 72\"", "capacity": "Up to 3000 TPH", "belt_speed": "100-600 FPM", "max_length": "2000 ft"}', true, true),
  
  ('Triple Offset Butterfly Valve TOB-600', 'triple-offset-butterfly-valve-tob-600', 'd4e5f6a7-b8c9-0123-def0-234567890123', 'Zero-leakage triple offset butterfly valve for critical isolation and control applications in process industries.', '<h3>Overview</h3><p>The TOB-600 Triple Offset Butterfly Valve provides bubble-tight shutoff for the most demanding isolation applications. The triple offset design eliminates seat wear and ensures long service life.</p><h3>Technical Specifications</h3><table><tr><th>Parameter</th><th>Value</th></tr><tr><td>Size Range</td><td>2" to 60"</td></tr><tr><td>Pressure Class</td><td>150-600 lb</td></tr><tr><td>Temperature</td><td>-50°F to 1200°F</td></tr><tr><td>Leakage Class</td><td>VI (Zero Leakage)</td></tr></table><h3>Features</h3><ul><li>Fire-safe design per API 607</li><li>Bidirectional sealing</li><li>Low operating torque</li><li>Multiple material options</li></ul>', '{"size_range": "2\" to 60\"", "pressure_class": "150-600 lb", "temperature": "-50°F to 1200°F", "leakage_class": "VI", "compliance": ["API 607", "API 609"]}', true, true),
  
  ('Industrial Diesel Generator IDG-1000', 'industrial-diesel-generator-idg-1000', 'e5f6a7b8-c9d0-1234-ef01-345678901234', 'Reliable standby and prime power diesel generator set with automatic transfer switching for critical facility backup.', '<h3>Overview</h3><p>The IDG-1000 Industrial Diesel Generator provides dependable power for critical facilities. Designed for both standby and prime power applications with advanced controls and monitoring.</p><h3>Technical Specifications</h3><table><tr><th>Parameter</th><th>Value</th></tr><tr><td>Power Output</td><td>500-2000 kW</td></tr><tr><td>Voltage</td><td>208-480V 3-Phase</td></tr><tr><td>Fuel Consumption</td><td>25-100 GPH</td></tr><tr><td>Runtime</td><td>24+ Hours (with standard tank)</td></tr></table><h3>Features</h3><ul><li>Tier 4 Final emissions compliant</li><li>Automatic transfer switch integration</li><li>Remote monitoring and control</li><li>Sound-attenuated enclosure options</li></ul>', '{"power_output": "500-2000 kW", "voltage": "208-480V 3-Phase", "fuel_consumption": "25-100 GPH", "emissions": "Tier 4 Final"}', true, true),
  
  ('Overhead Bridge Crane OBC-50', 'overhead-bridge-crane-obc-50', 'f6a7b8c9-d0e1-2345-f012-456789012345', 'Double girder overhead bridge crane for heavy lifting applications in manufacturing and industrial facilities.', '<h3>Overview</h3><p>The OBC-50 Overhead Bridge Crane delivers precision lifting capability for heavy industrial applications. Double girder design provides maximum hook height and stability for demanding material handling.</p><h3>Technical Specifications</h3><table><tr><th>Parameter</th><th>Value</th></tr><tr><td>Capacity</td><td>10-50 Tons</td></tr><tr><td>Span</td><td>30-120 ft</td></tr><tr><td>Lift Height</td><td>20-60 ft</td></tr><tr><td>Hoist Speed</td><td>5-20 FPM</td></tr></table><h3>Features</h3><ul><li>Variable frequency drives</li><li>Anti-sway control system</li><li>Wireless remote operation</li><li>CMAA Class D duty rating</li></ul>', '{"capacity": "10-50 Tons", "span": "30-120 ft", "lift_height": "20-60 ft", "hoist_speed": "5-20 FPM", "duty_class": "CMAA Class D"}', true, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO blog_posts (title, slug, excerpt, content, author, publish_date, is_published) VALUES
  ('Understanding Industrial Pump Selection: A Complete Guide', 'understanding-industrial-pump-selection-guide', 'Learn the critical factors in selecting the right industrial pump for your application, from flow requirements to material compatibility.', '<h2>Introduction</h2><p>Selecting the right industrial pump is crucial for operational efficiency and long-term reliability. This guide covers the essential considerations for pump selection in process industries.</p><h2>Key Selection Factors</h2><h3>1. Flow Requirements</h3><p>Understanding your flow rate requirements is the foundation of pump selection. Consider both normal operating conditions and peak demand scenarios.</p><h3>2. Head Requirements</h3><p>Total dynamic head includes static head, friction losses, and pressure requirements at the discharge point.</p><h3>3. Fluid Properties</h3><p>Consider viscosity, temperature, specific gravity, and any solids content that may affect pump performance and material selection.</p><h2>Pump Types Comparison</h2><table><tr><th>Type</th><th>Best For</th><th>Limitations</th></tr><tr><td>Centrifugal</td><td>High flow, low viscosity</td><td>Not self-priming</td></tr><tr><td>Positive Displacement</td><td>High viscosity, metering</td><td>Flow pulsation</td></tr><tr><td>Diaphragm</td><td>Corrosive fluids</td><td>Limited flow rates</td></tr></table><h2>Conclusion</h2><p>Proper pump selection requires careful analysis of your process requirements. Contact our engineering team for assistance with your specific application.</p>', 'Engineering Team', now() - interval '5 days', true),
  
  ('Preventive Maintenance Best Practices for Industrial Compressors', 'preventive-maintenance-industrial-compressors', 'Maximize compressor uptime and efficiency with these proven preventive maintenance strategies for industrial air systems.', '<h2>Introduction</h2><p>Industrial compressors represent significant capital investments. A robust preventive maintenance program protects this investment while ensuring reliable compressed air supply.</p><h2>Daily Checks</h2><ul><li>Monitor discharge pressure and temperature</li><li>Check oil level and condition</li><li>Inspect for unusual noises or vibrations</li><li>Verify drain operation</li></ul><h2>Weekly Maintenance</h2><ul><li>Clean or replace air intake filters</li><li>Check belt tension and condition</li><li>Inspect safety valve operation</li><li>Review operating logs for trends</li></ul><h2>Quarterly Service</h2><ul><li>Oil and filter change</li><li>Separator element inspection</li><li>Electrical connection inspection</li><li>Cooling system cleaning</li></ul><h2>Annual Overhaul</h2><p>Schedule comprehensive annual service including airend inspection, valve replacement, and control system calibration.</p>', 'Technical Services', now() - interval '12 days', true),
  
  ('Industry 4.0: Smart Manufacturing and Equipment Integration', 'industry-4-smart-manufacturing-equipment-integration', 'Explore how IoT sensors and data analytics are transforming industrial equipment monitoring and predictive maintenance.', '<h2>The Digital Transformation</h2><p>Industry 4.0 represents a fundamental shift in how industrial equipment is monitored, maintained, and optimized. Smart sensors and connectivity enable unprecedented visibility into equipment performance.</p><h2>Key Technologies</h2><h3>IoT Sensors</h3><p>Wireless sensors monitor vibration, temperature, pressure, and other critical parameters in real-time, enabling early detection of developing issues.</p><h3>Predictive Analytics</h3><p>Machine learning algorithms analyze sensor data to predict equipment failures before they occur, enabling proactive maintenance scheduling.</p><h3>Digital Twins</h3><p>Virtual models of physical equipment allow simulation of operating conditions and optimization of performance parameters.</p><h2>Implementation Benefits</h2><table><tr><th>Benefit</th><th>Typical Improvement</th></tr><tr><td>Unplanned Downtime</td><td>30-50% Reduction</td></tr><tr><td>Maintenance Costs</td><td>20-30% Reduction</td></tr><tr><td>Equipment Life</td><td>20-40% Extension</td></tr></table><h2>Getting Started</h2><p>Begin with high-value, critical equipment. Our team can help identify the best candidates for smart monitoring implementation.</p>', 'Innovation Team', now() - interval '20 days', true)
ON CONFLICT (slug) DO NOTHING;